global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8000']

  - job_name: 'movie-service'
    static_configs:
      - targets: ['movie-service:8000']

  - job_name: 'booking-service'
    static_configs:
      - targets: ['booking-service:8000']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8000']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8000']
